# !!! Important: This section controls site behavior and should not be changed without assistance from the web-team
site_name: iDEC Resources Wiki

theme:
  name: material
  logo: img/idec-logo-white-bg.png
  favicon: img/idec-logo.png

  palette:
    primary: deep purple
    accent: deep purple

  features:
    - header.autohide
    - navigation.tabs

repo_url: https://github.com/idechq/idec-wiki

edit_uri: blob/main/docs/

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - admonition

plugins:
  - search
  - mermaid2
  - section-index

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2021 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

# This section below can be changed to update the navigation menu of the wiki

nav:
  - Home: index.md
  - Resources:
      - Introduction:
          - resources/introduction.md
      - Creating genetic diversity:
          - resources/genetic_diversity.md
          - Error-prone PCR: resources/epPCR.md
          - Recombinatorial gene and domain shuffling: resources/gene_shuttling.md
      - Laboratory selection methods:
          - resources/lab_selection_methods.md
          - Selection of binders:
              - resources/binders.md
              - Phage display: resources/phage_display.md
              - Cell surface display: resources/FACS_FADS.md
              - Ribosome display: resources/ribodisplay.md
              - cDNA display & mRNA display: resources/mRNAdisplay.md
              - CIS display: resources/cisdisplay.md
              - SELEX: resources/selex.md
          - Selection of enzymes and reporters:
              - resources/enzymes.md
              - By survival: resources/survival.md
              - By biochemical assays: resources/biochem.md
              - By in vitro compartmentalisation: resources/CSR_SBL.md
      - Continuous directed evolution methods:
          - resources/cont_de_methods.md
          - PACE: resources/PACE_PANCE.md
          - In situ targeted mutagenesis: resources/insitu_mut.md
      - Computational tools:
          - resources/computational_tools.md
      - Genome Evolution:
          - resources/genome_evolution.md
          - MAGE: resources/mage.md
          - Adaptive Laboratory Evolution: resources/ALE.md
          - Scramble: resources/scramble.md
  - Team Wiki:
      - List of team wikis: team_wiki/wiki_list.md
      - Setting up your team wiki: team_wiki/setup_wiki.md
      - Accessing your team wiki repository: team_wiki/access_repo.md
      - Configuring your GitHub Pages: team_wiki/gh_pages.md
      - Default wiki tutorial:
          - MkDocs & Material for MkDocs: team_wiki/mkdocs.md
          - Fork a repository: team_wiki/fork.md
          - Environment for editing: team_wiki/envr.md
          - MkDocs common operations: team_wiki/operations.md
          - Stage, commit and push changes: team_wiki/push.md
          - Submit a pull request: team_wiki/pull_request.md
          - Moving forward: team_wiki/forward.md
