# !!! Important: This section controls site behavior and should not be changed without assistance from the web-team
site_name: iDEC Resources Wiki

theme:
    name: material
    logo: img/idec-logo-white-bg.png
    favicon: img/idec-logo.png

    palette:
        primary: deep purple
        accent: deep purple

    features:
        - header.autohide
        - navigation.expand

repo_url: https://github.com/idechq/idec-wiki

edit_uri: blob/main/docs/

markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.tabbed
    - abbr
    - pymdownx.snippets
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - meta
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tasklist:
          clickable_checkbox: true
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    - javascripts/tables.js
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2021 iDEC | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

# This section below can be changed to update the navigation menu of the wiki

nav:
    - Home: index.md
    - Introduction: introduction.md
    - Creating genetic diversity: genetic_diversity.md
    - Laboratory selection methods: lab_selection_methods.md
    - Continuous directed evolution methods: cont_de_methods.md
    - Computational tools: computational_tools.md
    - Genome Evolution: genome_evolution.md
    - SthSthSth:
        - Test page: about.md
